// https://www.sqlite.org/rescode.html

///|
pub const SQLITE_OK = 0

///|
pub const SQLITE_ERROR = 1

///|
pub const SQLITE_INTERNAL = 2

///|
pub const SQLITE_PERM = 3

///|
pub const SQLITE_ABORT = 4

///|
pub const SQLITE_BUSY = 5

///|
pub const SQLITE_LOCKED = 6

///|
pub const SQLITE_NOMEM = 7

///|
pub const SQLITE_READONLY = 8

///|
pub const SQLITE_INTERRUPT = 9

///|
pub const SQLITE_IOERR = 10

///|
pub const SQLITE_CORRUPT = 11

///|
pub const SQLITE_NOTFOUND = 12

///|
pub const SQLITE_FULL = 13

///|
pub const SQLITE_CANTOPEN = 14

///|
pub const SQLITE_PROTOCOL = 15

///|
pub const SQLITE_EMPTY = 16

///|
pub const SQLITE_SCHEMA = 17

///|
pub const SQLITE_TOOBIG = 18

///|
pub const SQLITE_CONSTRAINT = 19

///|
pub const SQLITE_MISMATCH = 20

///|
pub const SQLITE_MISUSE = 21

///|
pub const SQLITE_NOLFS = 22

///|
pub const SQLITE_AUTH = 23

///|
pub const SQLITE_FORMAT = 24

///|
pub const SQLITE_RANGE = 25

///|
pub const SQLITE_NOTADB = 26

///|
pub const SQLITE_NOTICE = 27

///|
pub const SQLITE_WARNING = 28

///|
pub const SQLITE_ROW = 100

///|
pub const SQLITE_DONE = 101

///|
pub const SQLITE_OK_LOAD_PERMANENTLY = 256

///|
pub const SQLITE_ERROR_MISSING_COLLSEQ = 257
